In [1]:
# import library

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# import data
df=pd.read_csv(r"C:\Users\Admin\Desktop\Viska\Machine Learning\Day-3-naive_bayes_1/naive_bayes_1.csv")
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin  
0                330911    7.8292   NaN  
1                363272    7.0000   NaN  
2                240276    9.6875   NaN  
3                315154    8.6625   NaN  
4               3101298   12.2875   NaN  
..                  ...       ...   ...  
413           A.5. 3236    8.0500   NaN  
414            PC 17758  108.9000  C105  
415  SOTON/O.Q. 3101262    7.2500   NaN  
416              359309    8.0500   NaN  
417                2668   22.3583   NaN  

[418 rows x 11 columns]

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
dtype: int64

In [4]:
df.iloc[2:7,2:6]

Pclass                                          Name     Sex   Age
2       2                     Myles, Mr. Thomas Francis    male  62.0
3       3                              Wirz, Mr. Albert    male  27.0
4       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0
5       3                    Svensson, Mr. Johan Cervin    male  14.0
6       3                          Connolly, Miss. Kate  female  30.0

In [5]:
len(df[df['Age']>50])

31

In [6]:
df[df['Age']>50]

PassengerId  Survived  Pclass  \
2            894         0       2   
13           905         0       2   
20           912         0       1   
48           940         1       1   
69           961         1       1   
77           969         1       1   
81           973         0       1   
96           988         1       1   
114         1006         1       1   
131         1023         0       1   
142         1034         0       1   
152         1044         0       3   
177         1069         0       1   
179         1071         1       1   
193         1085         0       2   
213         1105         1       2   
217         1109         0       1   
224         1116         1       1   
236         1128         0       1   
240         1132         1       1   
293         1185         0       1   
305         1197         1       1   
308         1200         0       1   
314         1206         1       1   
316         1208         0       1   
343         1235         1       1   
356         1248         1       1   
374         1266         1       1   
378         1270         0       1   
387         1279         0       2   
391         1283         1       1   

                                                  Name     Sex   Age  SibSp  \
2                            Myles, Mr. Thomas Francis    male  62.0      0   
13                                Howard, Mr. Benjamin    male  63.0      1   
20                              Rothschild, Mr. Martin    male  55.0      1   
48     Bucknell, Mrs. William Robert (Emma Eliza Ward)  female  60.0      0   
69                 Fortune, Mrs. Mark (Mary McDougald)  female  60.0      1   
77   Cornell, Mrs. Robert Clifford (Malvina Helen L...  female  55.0      2   
81                                  Straus, Mr. Isidor    male  67.0      1   
96   Cavendish, Mrs. Tyrell William (Julia Florence...  female  76.0      1   
114             Straus, Mrs. Isidor (Rosalie Ida Blun)  female  63.0      1   
131                          Gracie, Col. Archibald IV    male  53.0      0   
142                         Ryerson, Mr. Arthur Larned    male  61.0      1   
152                                 Storey, Mr. Thomas    male  60.5      0   
177                    Stengel, Mr. Charles Emil Henry    male  54.0      1   
179  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  female  64.0      0   
193                                  Lingane, Mr. John    male  61.0      0   
213       Howard, Mrs. Benjamin (Ellen Truelove Arman)  female  60.0      1   
217                           Wick, Mr. George Dennick    male  57.0      1   
224   Candee, Mrs. Edward (Helen Churchill Hungerford)  female  53.0      0   
236                           Warren, Mr. Frank Manley    male  64.0      1   
240          Lindstrom, Mrs. Carl Johan (Sigrid Posse)  female  55.0      0   
293                              Dodge, Dr. Washington    male  53.0      1   
305  Crosby, Mrs. Edward Gifford (Catherine Elizabe...  female  64.0      1   
308                         Hays, Mr. Charles Melville    male  55.0      1   
314              White, Mrs. John Stuart (Ella Holmes)  female  55.0      0   
316                      Spencer, Mr. William Augustus    male  57.0      1   
343  Cardeza, Mrs. James Warburton Martinez (Charlo...  female  58.0      0   
356     Brown, Mrs. John Murray (Caroline Lane Lamson)  female  59.0      2   
374              Dodge, Mrs. Washington (Ruth Vidaver)  female  54.0      1   
378                        Hipkins, Mr. William Edward    male  55.0      0   
387                                    Ashby, Mr. John    male  57.0      0   
391     Lines, Mrs. Ernest H (Elizabeth Lindsey James)  female  51.0      0   

     Parch    Ticket      Fare            Cabin  
2        0    240276    9.6875              NaN  
13       0     24065   26.0000              NaN  
20       0  PC 17603   59.4000              NaN  
48       0     11813   76.2917              D15  
69       

In [7]:
Age=df['Age']
Age

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ... 
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64

In [8]:
Age[(Age<20) | (Age>70)] 

5      14.0
8      18.0
21      9.0
35     18.5
55     10.0
       ... 
389     6.0
392    13.0
395    18.0
403    17.0
409     3.0
Name: Age, Length: 62, dtype: float64

In [9]:
len(Age[(Age<20) | (Age>70)] )

62

In [10]:
df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Fare"],axis=1,inplace=True)
df

Survived  Pclass     Sex   Age
0           0       3    male  34.5
1           1       3  female  47.0
2           0       2    male  62.0
3           0       3    male  27.0
4           1       3  female  22.0
..        ...     ...     ...   ...
413         0       3    male   NaN
414         1       1  female  39.0
415         0       3    male  38.5
416         0       3    male   NaN
417         0       3    male   NaN

[418 rows x 4 columns]

In [11]:
df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
df.Age.values

array([34.5 , 47.  , 62.  , 27.  , 22.  , 14.  , 30.  , 26.  , 18.  ,
       21.  ,   nan, 46.  , 23.  , 63.  , 47.  , 24.  , 35.  , 21.  ,
       27.  , 45.  , 55.  ,  9.  ,   nan, 21.  , 48.  , 50.  , 22.  ,
       22.5 , 41.  ,   nan, 50.  , 24.  , 33.  ,   nan, 30.  , 18.5 ,
         nan, 21.  , 25.  ,   nan, 39.  ,   nan, 41.  , 30.  , 45.  ,
       25.  , 45.  ,   nan, 60.  , 36.  , 24.  , 27.  , 20.  , 28.  ,
         nan, 10.  , 35.  , 25.  ,   nan, 36.  , 17.  , 32.  , 18.  ,
       22.  , 13.  ,   nan, 18.  , 47.  , 31.  , 60.  , 24.  , 21.  ,
       29.  , 28.5 , 35.  , 32.5 ,   nan, 55.  , 30.  , 24.  ,  6.  ,
       67.  , 49.  ,   nan,   nan,   nan, 27.  , 18.  ,   nan,  2.  ,
       22.  ,   nan, 27.  ,   nan, 25.  , 25.  , 76.  , 29.  , 20.  ,
       33.  , 43.  , 27.  ,   nan, 26.  , 16.  , 28.  , 21.  ,   nan,
         nan, 18.5 , 41.  ,   nan, 36.  , 18.5 , 63.  , 18.  ,   nan,
        1.  , 36.  , 29.  , 12.  ,   nan, 35.  , 28.  ,   nan, 17.  ,
       22.  ,   nan,

In [13]:
df.Sex.values

array(['male', 'female', 'male', 'male', 'female', 'male', 'female',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'female', 'male', 'male', 'male', 'female', 'female',
       'male', 'male', 'female', 'female', 'male', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'female', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'female', 'male', 'female',
       'male',

In [14]:
inputs=df.drop(["Survived","Sex"],axis="columns")
inputs.head()
               

Pclass   Age
0       3  34.5
1       3  47.0
2       2  62.0
3       3  27.0
4       3  22.0

In [15]:
Target=df.Survived
Target.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [16]:
y=df.Sex
y.head()

0      male
1    female
2      male
3      male
4    female
Name: Sex, dtype: object

In [17]:
y=y.map({"male":0,"female":1})
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Sex, dtype: int64

In [18]:
inputs=pd.concat([inputs,y],axis=1)
inputs

Pclass   Age  Sex
0         3  34.5    0
1         3  47.0    1
2         2  62.0    0
3         3  27.0    0
4         3  22.0    1
..      ...   ...  ...
413       3   NaN    0
414       1  39.0    1
415       3  38.5    0
416       3   NaN    0
417       3   NaN    0

[418 rows x 3 columns]

In [19]:
# find null value in any columns
inputs.columns[inputs.isna().any()]


Index(['Age'], dtype='object')

In [20]:
# to find null value
inputs.Age[:20]

0     34.5
1     47.0
2     62.0
3     27.0
4     22.0
5     14.0
6     30.0
7     26.0
8     18.0
9     21.0
10     NaN
11    46.0
12    23.0
13    63.0
14    47.0
15    24.0
16    35.0
17    21.0
18    27.0
19    45.0
Name: Age, dtype: float64

In [22]:
# fill null value help of the mean

inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

Pclass   Age  Sex
0       3  34.5    0
1       3  47.0    1
2       2  62.0    0
3       3  27.0    0
4       3  22.0    1
5       3  14.0    0
6       3  30.0    1
7       2  26.0    0
8       3  18.0    1
9       3  21.0    0

In [24]:
# split data into train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,Target, test_size=0.3)

In [25]:
len(x_train)

292

In [26]:
len(x_test)

126

In [27]:
len(inputs)

418

In [28]:
# to see x_train data
x_train

Pclass       Age  Sex
38        3  25.00000    0
100       1  43.00000    1
217       1  57.00000    0
162       2  26.00000    1
29        3  30.27259    0
..      ...       ...  ...
277       2  40.00000    0
105       3  28.00000    0
262       2  29.00000    1
234       1  39.00000    0
294       3  36.00000    0

[292 rows x 3 columns]

In [29]:
# to see x_test data
x_test

Pclass       Age  Sex
216       3  30.27259    1
282       3  30.27259    1
325       3  23.00000    0
309       3  45.00000    1
17        3  21.00000    0
..      ...       ...  ...
310       3  18.00000    0
346       2  26.00000    0
160       3  30.27259    1
312       3  30.27259    0
115       3  18.00000    0

[126 rows x 3 columns]

In [30]:
# create model
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [31]:
# train model
model.fit(x_train,y_train)

GaussianNB()

In [32]:
# to compare y_test to predict x_test
y_test[:10]

216    1
282    1
325    0
309    1
17     0
285    0
155    0
123    0
213    1
381    0
Name: Survived, dtype: int64

In [55]:
model.predict(x_test[:10])


array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [34]:
model.predict_proba(x_test[:10])

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [56]:
model.predict([[1,25,0]])

array([0], dtype=int64)

In [51]:
model.score(x_test,y_test)*100

100.0

In [41]:
# Naive Bayes modelscore
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
print(" Naive Bayes accuracy : {:.2f}%".format(nb.score(x_test,y_test)*100))

 Naive Bayes accuracy : 100.00%
