In [1]:
#import library
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
#import data
df=pd.read_csv(r"C:\Users\Admin\Desktop\Viska\Machine Learning\Day-9-Decision Tree/D_tree.csv")
df.head()

Company                  Job     Degree  Salary_more_then_100k
0  Google      Sales executive  Bachelors                      0
1  Google      Sales executive    Masters                      0
2  Google     Business manager  Bachelors                      1
3  Google     Business manager    Masters                      1
4  Google  Computer programmer  Bachelors                      0

In [3]:
df.tail()

Company                  Job     Degree  Salary_more_then_100k
11  Facebook      Sales executive    Masters                      1
12  Facebook     Business manager  Bachelors                      1
13  Facebook     Business manager    Masters                      1
14  Facebook  Computer programmer  Bachelors                      1
15  Facebook  Computer programmer    Masters                      1

In [4]:
df.isnull().sum()

Company                  0
Job                      0
Degree                   0
Salary_more_then_100k    0
dtype: int64

In [5]:
df.isnull().any()

Company                  False
Job                      False
Degree                   False
Salary_more_then_100k    False
dtype: bool

In [6]:
df.dtypes

Company                  object
Job                      object
Degree                   object
Salary_more_then_100k     int64
dtype: object

In [8]:
df['Job'].dtypes

dtype('O')

In [9]:
df['Company'].dtypes

dtype('O')

In [10]:
df.describe()

Salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [11]:
df.describe(include='all')

Company               Job     Degree  Salary_more_then_100k
count       16                16         16                 16.000
unique       3                 3          2                    NaN
top     Google  Business manager  Bachelors                    NaN
freq         6                 6          8                    NaN
mean       NaN               NaN        NaN                  0.625
std        NaN               NaN        NaN                  0.500
min        NaN               NaN        NaN                  0.000
25%        NaN               NaN        NaN                  0.000
50%        NaN               NaN        NaN                  1.000
75%        NaN               NaN        NaN                  1.000
max        NaN               NaN        NaN                  1.000

In [12]:
df.shape

(16, 4)

In [13]:
df.shape[0]

16

In [14]:
df.shape[1]

4

In [15]:
df.drop_duplicates(inplace=True)
df

Company                  Job     Degree  Salary_more_then_100k
0       Google      Sales executive  Bachelors                      0
1       Google      Sales executive    Masters                      0
2       Google     Business manager  Bachelors                      1
3       Google     Business manager    Masters                      1
4       Google  Computer programmer  Bachelors                      0
5       Google  Computer programmer    Masters                      1
6   Abc pharma      Sales executive    Masters                      0
7   Abc pharma  Computer programmer  Bachelors                      0
8   Abc pharma     Business manager  Bachelors                      0
9   Abc pharma     Business manager    Masters                      1
10    Facebook      Sales executive  Bachelors                      1
11    Facebook      Sales executive    Masters                      1
12    Facebook     Business manager  Bachelors                      1
13    Facebook     Business manager    Masters                      1
14    Facebook  Computer programmer  Bachelors                      1
15    Facebook  Computer programmer    Masters                      1

In [16]:
# drop dependent variable
target=df.drop(["Company","Job","Degree"], axis="columns")
target

Salary_more_then_100k
0                       0
1                       0
2                       1
3                       1
4                       0
5                       1
6                       0
7                       0
8                       0
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      1

In [17]:
inputs = pd.concat([df.Company,df.Job,df.Degree], axis = 1)
inputs.head()

Company                  Job     Degree
0  Google      Sales executive  Bachelors
1  Google      Sales executive    Masters
2  Google     Business manager  Bachelors
3  Google     Business manager    Masters
4  Google  Computer programmer  Bachelors

In [18]:
inputs.Company.unique()

array(['Google', 'Abc pharma', 'Facebook'], dtype=object)

In [19]:
x=inputs.Company
x.head()

0    Google
1    Google
2    Google
3    Google
4    Google
Name: Company, dtype: object

In [20]:
x=x.map({"Google":0,"Abc pharma":1,"Facebook":2})
x.head()

0    0
1    0
2    0
3    0
4    0
Name: Company, dtype: int64

In [21]:
inputs.Job.unique()

array(['Sales executive', 'Business manager', 'Computer programmer'],
      dtype=object)

In [22]:
y=inputs.Job
y.head()

0        Sales executive
1        Sales executive
2       Business manager
3       Business manager
4    Computer programmer
Name: Job, dtype: object

In [23]:
y=y.map({"Sales executive":0,"Business manager":1,"Computer programmer":2})
y.head()

0    0
1    0
2    1
3    1
4    2
Name: Job, dtype: int64

In [24]:
inputs.Degree.unique()

array(['Bachelors', 'Masters'], dtype=object)

In [25]:
z=inputs.Degree
z.head()

0    Bachelors
1      Masters
2    Bachelors
3      Masters
4    Bachelors
Name: Degree, dtype: object

In [26]:
z=z.map({"Bachelors":0,"Masters":1})
z.head()

0    0
1    1
2    0
3    1
4    0
Name: Degree, dtype: int64

In [27]:
inputs_n = pd.concat([target,x,y,z], axis = 1)
inputs_n.head()

Salary_more_then_100k  Company  Job  Degree
0                      0        0    0       0
1                      0        0    0       1
2                      1        0    1       0
3                      1        0    1       1
4                      0        0    2       0

In [28]:
df1=inputs_n.drop(["Salary_more_then_100k"], axis="columns")
df1.head()

Company  Job  Degree
0        0    0       0
1        0    0       1
2        0    1       0
3        0    1       1
4        0    2       0

In [29]:
# dependent variable fit in target
target_n = df.Salary_more_then_100k
target_n.head()

0    0
1    0
2    1
3    1
4    0
Name: Salary_more_then_100k, dtype: int64

In [31]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [33]:
model.fit(df1,target_n)

DecisionTreeClassifier()

In [34]:
# company
# 0- google
# 1- abc pharma
# 2- facebook

# job
# 0 - sales executive
# 1 - business manager  
# 2 - computer programmer

# degree
#  0 - bachelors
# 1 - master

In [35]:
model.predict([[1,1,0]])

array([0], dtype=int64)

In [36]:
model.predict([[2,2,0]])

array([1], dtype=int64)

In [38]:
model.predict([[2,1,0]])

array([1], dtype=int64)

In [41]:
model.score(df1,target_n)*100

100.0