In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
#input data
    x=pd.DataFrame(iris['data'],columns=iris['feature_names'])
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
#output data
y=iris['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
x.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,train_size=0.75,random_state=0)

In [11]:
print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


In [12]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


In [13]:
x.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [14]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         112.000000        112.000000         112.000000   
mean            5.886607          3.051786           3.796429   
std             0.871314          0.436196           1.800697   
min             4.300000          2.000000           1.100000   
25%             5.100000          2.800000           1.575000   
50%             5.800000          3.000000           4.250000   
75%             6.500000          3.300000           5.200000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        112.000000  
mean           1.223214  
std            0.781427  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.900000  
max            2.500000

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)

x_train_sc=sc.transform(x_train)

In [16]:
x_train_sc

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.55797625e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.98410911e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12707506e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31530348e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38416753e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -8.01118523e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31530348e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.86933568e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41436341e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.64126001e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.55797625e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
      

In [17]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
61                 5.9               3.0                4.2               1.5
92                 5.8               2.6                4.0               1.2
112                6.8               3.0                5.5               2.1
2                  4.7               3.2                1.3               0.2
141                6.9               3.1                5.1               2.3
..                 ...               ...                ...               ...
9                  4.9               3.1                1.5               0.1
103                6.3               2.9                5.6               1.8
67                 5.8               2.7                4.1               1.0
117                7.7               3.8                6.7               2.2
47                 4.6               3.2                1.4               0.2

[112 rows x 4 columns]

#model building 


#In adaboost you can change the individual model apart from decision tree


In [18]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression

In [19]:
# inside adaboost algorithm, running logistic regression.
# HERE WE CREATE 150 LOGISTIC REGREESION COMBINATION AND make ADABOOSTCLASSIFIER.
model2=AdaBoostClassifier(estimator=LogisticRegression(),n_estimators=150)

In [20]:
model2.fit(x_train,y_train)

AdaBoostClassifier(estimator=LogisticRegression(), n_estimators=150)

In [21]:
y_pred=model2.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2])

In [22]:
#Accuracy_score
from sklearn.metrics import accuracy_score,confusion_matrix

In [23]:
print(accuracy_score(y_test,y_pred)*100)

92.10526315789474


In [24]:
print(confusion_matrix(y_test,y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  2  7]]


In [25]:
print(confusion_matrix(y_test,y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  2  7]]
