In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn import linear_model
import matplotlib.pyplot as plt

assignment - 1 (simple linear regression)


gold price prediction
 
year = 2020
year = 2025

In [2]:
#import data
df1=pd.read_csv(r"C:\Users\Admin\Desktop\Viska\Machine Learning\Assignment/assignment_1_linear.csv")
df1

Year  Gold_price
0  2016       30000
1  2018       35000
2  2019       40000
3  2021       45000
4  2022       50000

In [3]:
#remove dependent data
new_df=df1.drop('Gold_price',axis=1)
new_df

Year
0  2016
1  2018
2  2019
3  2021
4  2022

In [4]:
model=linear_model.LinearRegression()
model.fit(new_df,df1.Gold_price)

LinearRegression()

In [5]:
model.predict([[2020]])

array([42631.57894737])

In [6]:
model.predict([[2025]])

array([59078.94736842])

assignment - 2 (multiple linear regression)

experience = 10
test score = 10
interview score = 10


experience = 10
test score = 5
interview score = 5

In [7]:
#import data
df=pd.read_csv(r"C:\Users\Admin\Desktop\Viska\Machine Learning\Assignment/assignment_2_linear.csv")
df

experience  test_score  interview_score  salary
0         NaN           8                9   50000
1         NaN           8                6   45000
2         5.0           6                7   60000
3         2.0          10               10   65000
4         7.0           9                6   70000
5         3.0           7               10   62000
6        10.0           8                7   72000
7        11.0           7                8   80000

In [8]:
#fill the null value
df.loc[0,'experience']=9
df.loc[1,'experience']=8
df

experience  test_score  interview_score  salary
0         9.0           8                9   50000
1         8.0           8                6   45000
2         5.0           6                7   60000
3         2.0          10               10   65000
4         7.0           9                6   70000
5         3.0           7               10   62000
6        10.0           8                7   72000
7        11.0           7                8   80000

In [9]:
#remove dependent variable
new_df=df.drop('salary',axis=1)
new_df

experience  test_score  interview_score
0         9.0           8                9
1         8.0           8                6
2         5.0           6                7
3         2.0          10               10
4         7.0           9                6
5         3.0           7               10
6        10.0           8                7
7        11.0           7                8

In [10]:
model=linear_model.LinearRegression()
model.fit(new_df,df.salary)

LinearRegression()

In [11]:
model.predict([[10,10,10]])

array([69961.14001565])

In [12]:
model.predict([[10,5,5]])

array([61268.06022377])