**Nitesh _Assignment_4_Naive_ML**

In [1]:
# import library

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# import data
df=pd.read_excel(r"C:\Users\Admin\Desktop\Viska\Machine Learning\Assignment/assignment_4_naive.xlsx")
df

PassengerId  Survived  Pclass                          Name     Sex  \
0           1191         0       3           Johansson, Mr. Nils    male   
1           1192         0       3     Olsson, Mr. Oscar Wilhelm    male   
2           1193         0       2           Malachard, Mr. Noel    male   
3           1194         0       2   Phillips, Mr. Escott Robert    male   
4           1195         0       3             Pokrnic, Mr. Tome    male   
..           ...       ...     ...                           ...     ...   
114         1305         0       3            Spector, Mr. Woolf    male   
115         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
116         1307         0       3  Saether, Mr. Simon Sivertsen    male   
117         1308         0       3           Ware, Mr. Frederick    male   
118         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare  
0    29.0      0      0              347467    7.8542  
1    32.0      0      0              347079    7.7750  
2     NaN      0      0              237735   15.0458  
3    43.0      0      1         S.O./P.P. 2   21.0000  
4    24.0      0      0              315092    8.6625  
..    ...    ...    ...                 ...       ...  
114   NaN      0      0           A.5. 3236    8.0500  
115  39.0      0      0            PC 17758  108.9000  
116  38.5      0      0  SOTON/O.Q. 3101262    7.2500  
117   NaN      0      0              359309    8.0500  
118   NaN      1      1                2668   22.3583  

[119 rows x 10 columns]

In [3]:
df.shape

(119, 10)

In [4]:
df.shape[0]

119

In [5]:
df.shape[1]

10

In [6]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            19
SibSp           0
Parch           0
Ticket          0
Fare            0
dtype: int64

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare'],
      dtype='object')

In [8]:
len(df['Age'])

119

In [9]:
len(df['Pclass'])

119

In [10]:
df.head()

PassengerId  Survived  Pclass                         Name   Sex   Age  \
0         1191         0       3          Johansson, Mr. Nils  male  29.0   
1         1192         0       3    Olsson, Mr. Oscar Wilhelm  male  32.0   
2         1193         0       2          Malachard, Mr. Noel  male   NaN   
3         1194         0       2  Phillips, Mr. Escott Robert  male  43.0   
4         1195         0       3            Pokrnic, Mr. Tome  male  24.0   

   SibSp  Parch       Ticket     Fare  
0      0      0       347467   7.8542  
1      0      0       347079   7.7750  
2      0      0       237735  15.0458  
3      0      1  S.O./P.P. 2  21.0000  
4      0      0       315092   8.6625

In [11]:
new_df=df.drop(['PassengerId','Name','SibSp','Ticket','Fare','Parch'],axis=1)
new_df.head()

Survived  Pclass   Sex   Age
0         0       3  male  29.0
1         0       3  male  32.0
2         0       2  male   NaN
3         0       2  male  43.0
4         0       3  male  24.0

In [12]:
new_df.Age.values

array([29.  , 32.  ,   nan, 43.  , 24.  ,   nan, 64.  , 30.  ,  0.83,
       55.  , 45.  , 18.  , 22.  ,   nan, 37.  , 55.  , 17.  , 57.  ,
       19.  , 27.  , 22.  , 26.  , 25.  , 26.  , 33.  , 39.  , 23.  ,
       12.  , 46.  , 29.  , 21.  , 48.  , 39.  ,   nan, 19.  , 27.  ,
       30.  , 32.  , 39.  , 25.  ,   nan, 18.  , 32.  ,   nan, 58.  ,
         nan, 16.  , 26.  , 38.  , 24.  , 31.  , 45.  , 25.  , 18.  ,
       49.  ,  0.17, 50.  , 59.  ,   nan,   nan, 30.  , 14.5 , 24.  ,
       31.  , 27.  , 25.  ,   nan,   nan, 22.  , 45.  , 29.  , 21.  ,
       31.  , 49.  , 44.  , 54.  , 45.  , 22.  , 21.  , 55.  ,  5.  ,
         nan, 26.  ,   nan, 19.  ,   nan, 24.  , 24.  , 57.  , 21.  ,
        6.  , 23.  , 51.  , 13.  , 47.  , 29.  , 18.  , 24.  , 48.  ,
       22.  , 31.  , 30.  , 38.  , 22.  , 17.  , 43.  , 20.  , 23.  ,
       50.  ,   nan,  3.  ,   nan, 37.  , 28.  ,   nan, 39.  , 38.5 ,
         nan,   nan])

In [14]:
inputs=new_df.drop(["Survived","Sex"],axis=1)
inputs.head()

Pclass   Age
0       3  29.0
1       3  32.0
2       2   NaN
3       2  43.0
4       3  24.0

In [15]:
Target=df.Survived
Target.head()

0    0
1    0
2    0
3    0
4    0
Name: Survived, dtype: int64

In [17]:
y=df.Sex
y

0        male
1        male
2        male
3        male
4        male
        ...  
114      male
115    female
116      male
117      male
118      male
Name: Sex, Length: 119, dtype: object

In [18]:
y=y.map({"male":0,"female":1})
y

0      0
1      0
2      0
3      0
4      0
      ..
114    0
115    1
116    0
117    0
118    0
Name: Sex, Length: 119, dtype: int64

In [19]:
inputs=pd.concat([inputs,y],axis=1)
inputs

Pclass   Age  Sex
0         3  29.0    0
1         3  32.0    0
2         2   NaN    0
3         2  43.0    0
4         3  24.0    0
..      ...   ...  ...
114       3   NaN    0
115       1  39.0    1
116       3  38.5    0
117       3   NaN    0
118       3   NaN    0

[119 rows x 3 columns]

In [21]:
inputs.isnull().sum()

Pclass     0
Age       19
Sex        0
dtype: int64

In [22]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs

Pclass    Age  Sex
0         3  29.00    0
1         3  32.00    0
2         2  30.91    0
3         2  43.00    0
4         3  24.00    0
..      ...    ...  ...
114       3  30.91    0
115       1  39.00    1
116       3  38.50    0
117       3  30.91    0
118       3  30.91    0

[119 rows x 3 columns]

In [23]:
inputs.isnull().sum()

Pclass    0
Age       0
Sex       0
dtype: int64

In [24]:
# split data into train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,Target, test_size=0.3)


In [25]:
len(x_train)

83

In [27]:
len(x_test)

36

In [28]:
# create model
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [29]:
model.fit(x_train,y_train)

GaussianNB()

In [32]:
x_test.head()

Pclass   Age  Sex
18        2  19.0    0
9         1  55.0    0
75        1  54.0    1
103       1  22.0    1
91        1  23.0    0

In [30]:
model.predict(x_test)

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [33]:
model.predict([[1,43,0]])

array([0], dtype=int64)

In [34]:
model.predict([[1,70,1]])

array([1], dtype=int64)

In [36]:
model.score(x_test,y_test)*100

100.0