1. find out mean?
   [10,25,48,75,98,65,85,95]


In [1]:
import numpy as np
x=[10,25,48,75,98,65,85,95]
y=np.mean(x)
print(y)

62.625


2. find out median?
   [10,20,30,45,47,85,96,25,32,14,52]

In [2]:
import numpy as np

x=[10,20,30,45,47,85,96,25,32,14,52]
y=np.sort(x)
print(y)

x=[10,20,30,45,47,85,96,25,32,14,52]
y=np.median(x)
print(y)



[10 14 20 25 30 32 45 47 52 85 96]
32.0


3. find out range?
   [45,75,65,25,32,12,45,85,69]

In [3]:
import numpy as np
x=[45,75,65,25,32,12,45,85,69]
y=np.sort(x)
print(y)

x=[45,75,65,25,32,12,45,85,69]
y=np.ptp(x)
print(y)

#Range=85-12=73

[12 25 32 45 45 65 69 75 85]
73


4.find out 45 percentile?
  [25,14,85,95,35,65,74,58,65,32,14,25,25]

In [4]:
import numpy as np
value=[25,14,85,95,35,65,74,58,65,32,14,25,25]
y=np.percentile(value,45)
print(y)

33.2


#5. what is normal distribution ?
#Ans:-Nortmal distribution is an important probability distribution used in statistics.it is a symmetric where same values will partain in both side in decresing order and mean & mean values will be same.

6.find out qurantile?
  [10,20,30,40,50,60,70,75,80]

In [5]:
import numpy as np
value=[10,20,30,40,50,60,70,75,80]
y=np.quantile(value,[0,0.25,0.5,0.75,1])
print(y)


[10. 30. 50. 70. 80.]


7.find out standard deviation?
  [45,78,95,65,32,52,41,47,48,48]

In [6]:
import numpy as np
x=[45,78,95,65,32,52,41,47,48,48]
y=np.std(x)
print(y)

17.958006570886422


8. find out mode?
  [10,20,30,47,52,69,52,52,63,63]

In [7]:
from statistics import mode
x=[10,20,30,47,52,69,52,52,63,63]
y=mode(x)
print(y)

from statistics import multimode
x=[10,20,30,47,52,69,52,52,63,63]
y=multimode(x)
print(y)

52
[52]


9.find out skewness is postive or negative?
  74,78,59,25,63,21,58,74,12,58,89,41 

In [8]:
from scipy.stats import skew
data=[74,78,59,25,63,21,58,74,12,58,89,41]
print(skew(data,axis=0))

-0.449146572979275


10.find out regresion 

 Area	PRICE
2600	550000
3000	565000
3200	610000
3600	680000
4000	725000

Here we have to find out if area=3300 square, predict home price?
Here we have to find out if area=5000 square, predict home price?

In [9]:
#import data
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn import linear_model
import matplotlib.pyplot as plt

df=pd.read_csv(r"C:\Users\Admin\Desktop\Viska\Machine Learning/linear_regression.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [10]:
#remove dependent variable
new_df=df.drop("price",axis=1)
new_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [11]:
model=linear_model.LinearRegression()
model.fit(new_df,df.price)

LinearRegression()

In [12]:
model.predict([[3300]])

array([628715.75342466])

In [13]:
model.predict([[5000]])

array([859554.79452055])