In [2]:
import numpy as nd
arr=nd.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


In [4]:
import numpy as nd 
arr=nd.array(1)
print(arr)
print(arr.ndim)
#can we put my multipal values in 0-D

1
0


In [9]:
import numpy as nd 
arr= nd.array([1,2,3,4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [11]:
import numpy as nd
arr = nd.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

import numpy as nd
arr = nd.array([[1,2,3]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2
[[1 2 3]]
2


In [12]:
import numpy as nd 
arr=nd.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,8]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 5 8]]]
3


In [14]:
import numpy as nd
arr = nd.array([1,2,3],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [16]:
import numpy as nd 
arr = nd.array([1,2,3,4,5])
print(arr[3]+arr[2])

7


In [18]:
import numpy as nd 
arr=nd.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9


In [23]:
import numpy as nd 
arr=nd.array([1,2,3,4,5,6,7,8,9,2])
a=arr.reshape(5,2)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 2]]


In [25]:
#Numpy joininf array
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
a=np.concatenate((arr1,arr2))
print(a)

[1 2 3 4 5 6 7 8]


import numpy as np


#Jupter note book

In [26]:
emp=np.empty((4,6))

In [27]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.37962320e-306, 1.29060871e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.02361614e-306, 1.78020848e-306, 1.78021527e-306,
        1.69119330e-306, 9.79101082e-307, 1.78020576e-306]])

In [29]:
emp_like=np.empty_like()
print(emp_like)

[1 2 3 4 5 6 7 8]


In [30]:
ide=np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
a=ide.shape
print(a)

(45, 45)


In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
a=arr.reshape(3,33)

In [40]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr=a.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [43]:
arr.shape

(99,)

In [45]:
arr=nd.array([1,2,3,4,5,6,7,8,9])
a=arr.reshape(3,3)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
a.sum(axis=0)

array([12, 15, 18])

In [47]:
a.sum(axis=1)

array([ 6, 15, 24])

In [49]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
for i in a.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [52]:
for i in a.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)